spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b103.p.ssafy.io:3306/farmcu?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: DB password
cloud:
  aws:
    credentials:
      access-key: aws access key
      secret-key: aws secret key
    s3: #버킷이름
      bucket: farmcu-bucket
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ssl password

OPENVIDU_URL: https://i8b103.p.ssafy.io:8443/
OPENVIDU_SECRET: openvidu password
